language: python

dist: xenial   # required for Python >= 3.7

python:
  - "3.7"

branches:

  only:
    - travis_intregrate

services:
  - docker

before_script:

  - docker-compose up --build

script:
  - pytest