version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dwellingly
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5431:5431"

  web:
    build: ./api
    ports: 
      - "5000:5000"
  
  
    
  


